// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6wmSO1d9pGonvyOkPm_I1CwxosJXIl8w',
    appId: '1:633495330328:web:4a2aae62bfcfcd3586ad6d',
    messagingSenderId: '633495330328',
    projectId: 'pinjamruangkrt',
    authDomain: 'pinjamruangkrt.firebaseapp.com',
    storageBucket: 'pinjamruangkrt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqyMDay5Bq4CFXI42xV5vl-xMWxiHcoJo',
    appId: '1:633495330328:android:efb9a1e853d169b386ad6d',
    messagingSenderId: '633495330328',
    projectId: 'pinjamruangkrt',
    storageBucket: 'pinjamruangkrt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAICwTtTuyd_U40gwEAgRRHi0HD85nbA4k',
    appId: '1:633495330328:ios:e4669436a4705a3d86ad6d',
    messagingSenderId: '633495330328',
    projectId: 'pinjamruangkrt',
    storageBucket: 'pinjamruangkrt.appspot.com',
    iosClientId: '633495330328-jdj66h12lqtqdihv2jddcbl84oh409cp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterKrtRuang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAICwTtTuyd_U40gwEAgRRHi0HD85nbA4k',
    appId: '1:633495330328:ios:e4669436a4705a3d86ad6d',
    messagingSenderId: '633495330328',
    projectId: 'pinjamruangkrt',
    storageBucket: 'pinjamruangkrt.appspot.com',
    iosClientId: '633495330328-jdj66h12lqtqdihv2jddcbl84oh409cp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterKrtRuang',
  );
}
